#!/usr/bin/env python

'''
script: run_diag

goal:  To allow a user to easily run the CAM diagnostics package from
       the command line.

Inputs:  The CAM diagnostics namelist file (in YAML format).  If the file is
         located in a different directory then the system path must also be
         included.

Any problems or issues with this script should be posted on the
DiscussCESM CAM forum located online here:

https://xenforo.cgd.ucar.edu/cesm/forums/cam.133/

Please note that registration may be required before a message can
be posted.  However, feel free to search the forums for similar issues
(and possible solutions) without needing to register or sign in.

Good luck, and may all your plots be helpful!
'''

#+++++++++++++++++++++
#Import python modules
#+++++++++++++++++++++

import sys
import argparse

###############################
#Input argument parser function
###############################

def parse_arguments():

    """
    Parses command-line input arguments using the argparse
    python module and outputs the final argument object.
    """

    #Create parser object:
    parser = argparse.ArgumentParser(description='Command-line wrapper to run the CAM diagnostics package.')

    #Add input arguments to be parsed:
    parser.add_argument('--namelist', metavar='<DIAG_YAML_FILE>', action='store', type=str,
                        help="namelist YAML file used to configure CAM diagnostics (see example_namelist.yaml)")

    #Parse Argument inputs
    args = parser.parse_args()
    return args

############################
#Main CAM diagnostics script
############################

#Run code below if command is called
#directly from the command line:
if __name__ == "__main__":

    #+++++++++++++++++++++
    #Begin CAM diag script
    #+++++++++++++++++++++
    print('CAM diagnostics is starting.')

    #+++++++++++++++++++++++++++++++++++++++++
    #Check that python is version 3 or greater
    #+++++++++++++++++++++++++++++++++++++++++

    if sys.version_info[0] < 3:
        errmsg = "Script only works with Python 3. Please switch python versions."
        print(errmsg, file=sys.stderr)
        sys.quit(1)

    #++++++++++++++++++++++++++++
    #Parse command-line arguments
    #++++++++++++++++++++++++++++

    args = parse_arguments()

    #Extract YAML namelist file name/path:
    namelist_yaml = args.namelist

    #++++++++++++++++++++++++++++++++
    #Call main CAM diagnostics method
    #++++++++++++++++++++++++++++++++

    #CONTINUE HERE!!

    #+++++++++++++++
    #End diag script
    #+++++++++++++++
    print('CAM diagnostics has completed successfully.')

