#!/usr/bin/env python

"""
script: run_diag

goal:  To allow a user to easily run the CAM diagnostics package from
       the command line.

Inputs:  The CAM diagnostics namelist file (in YAML format).  If the file is
         located in a different directory then the system path must also be
         included.

Any problems or issues with this script should be posted on the
DiscussCESM CAM forum located online here:

https://xenforo.cgd.ucar.edu/cesm/forums/cam.133/

Please note that registration may be required before a message can
be posted.  However, feel free to search the forums for similar issues
(and possible solutions) without needing to register or sign in.

Good luck, and may all your plots be helpful!
"""

#++++++++++++++++++++++++++++++
#Import standard python modules
#++++++++++++++++++++++++++++++

import os
import sys
import argparse

#+++++++++++++++++++++++++++++
#Import CAM diagnostics module
#+++++++++++++++++++++++++++++

#Determine local directory path:
_LOCAL_PATH = os.path.dirname(os.path.abspath(__file__))

#Add lib directory to path:
_DIAG_LIB_PATH = os.path.join(_LOCAL_PATH,"lib")

#Check that path actually exists:
if os.path.isdir(_DIAG_LIB_PATH):
    #If true, then add to Python path:
    sys.path.append(_DIAG_LIB_PATH)
else:
    #If not, then raise error:
    raise FileNotFoundError("'./lib' directory not found. Has 'run_diag' been moved?")

#Import CAM diagnostics object:
from CamDiag import CamDiag

#################
#Helper functions
#################

#++++++++++++++++++++++++++++++++
#Script message and exit function
#++++++++++++++++++++++++++++++++

def end_script(msg):

    """
    Prints message, and then exits script.
    """

    print("\n")
    print(msg)
    sys.exit(1)

#++++++++++++++++++++++++++++++
#Input argument parser function
#++++++++++++++++++++++++++++++

def parse_arguments():

    """
    Parses command-line input arguments using the argparse
    python module and outputs the final argument object.
    """

    #Create parser object:
    parser = argparse.ArgumentParser(description='Command-line wrapper to run the CAM diagnostics package.')

    #Add input arguments to be parsed:
    parser.add_argument('--namelist', metavar='<DIAG_YAML_FILE>', action='store', type=str,
                        help="namelist YAML file used to configure CAM diagnostics (see example_namelist.yaml)")

    #Parse Argument inputs
    args = parser.parse_args()
    return args

############################
#Main CAM diagnostics script
############################

#Run code below if command is called
#directly from the command line:
if __name__ == "__main__":

    #+++++++++++++++++++++
    #Begin CAM diag script
    #+++++++++++++++++++++
    print('CAM diagnostics is starting.')

    #+++++++++++++++++++++++++++++++++++++++++
    #Check that python is version 3 or greater
    #+++++++++++++++++++++++++++++++++++++++++

    if sys.version_info[0] < 3:
        end_script("Script only works with Python 3. Please switch python versions.")

    #++++++++++++++++++++++++++++
    #Parse command-line arguments
    #++++++++++++++++++++++++++++

    args = parse_arguments()

    #Extract YAML namelist file name/path:
    namelist_yaml = args.namelist

    #++++++++++++++++++++++++++++++++
    #Call main CAM diagnostics method
    #++++++++++++++++++++++++++++++++

    #CONTINUE HERE!!
    diag = CamDiag(namelist_yaml)

    #Create plots:
    diag.create_plots()

    #+++++++++++++++
    #End diag script
    #+++++++++++++++
    print('CAM diagnostics has completed successfully.')
    sys.exit(0)
