name: ldf_v0.01
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cartopy
  - cftime
  - dask
  - distributed
  - geocat-comp
  - geopandas
  - intake
  - intake-esm
  - intake-xarray
  - ipykernel
  - matplotlib
  - nc-time-axis
  - ncar-jobqueue
  - netcdf4
  - numpy
  - pip
  - python==3.11.4
  - uxarray
  - xarray
  - xesmf
  - yaml
  - zarr

